Pet_Health_Care_System/Pet_Cus_Info_Mng/urls.py
from django.urls import path
from . import views
from .views import (
    CustomerCreateView,CustomerUpdateView, CustomerDeleteView,
    PetCreateView, PetUpdateView, PetDeleteView,
    MedicalRecordListView, AppointmentListView,
    AppointmentFilterView, AppointmentCreateView
)

urlpatterns = [
    # Quản lý thú cưng
    path('petss/', views.pet_list, name='pet_listt'),  # Danh sách thú cưng
    path('petss/add/', PetCreateView.as_view(), name='pet_add'),  # Thêm thú cưng
    path('petss/<int:pk>/editt/', PetUpdateView.as_view(), name='pet_editt'),  # Sửa thú cưng
    path('petss/<int:pk>/deletee/', PetDeleteView.as_view(), name='pet_deletee'),  # Xóa thú cưng

    # Quản lý khách hàng
    path('customers/', views.customer_list, name='customer_list'),  # Danh sách khách hàng
    path('customers/add/', CustomerCreateView.as_view(), name='customer_add'),  # Thêm khách hàng
    path('customers/<int:pk>/edit/', CustomerUpdateView.as_view(), name='customer_edit'),  # Sửa khách hàng
    path('customers/<int:pk>/delete/', CustomerDeleteView.as_view(), name='customer_delete'),  # Xóa khách hàng

    # Quản lý lịch sử khám chữa bệnh
    path('petss/medicalRecords-history/<int:pet_id>/', MedicalRecordListView.as_view(), name='medicalRecords_history'),  # Lịch sử khám chữa bệnh

    # Quản lý lịch hẹn
    path('appointments-list/', AppointmentListView.as_view(), name='appointments_list'),
    path('customers/appointments-history/<str:email>/', AppointmentListView.as_view(), name='appointments_history'),  # Lịch hẹn
    path('appointments-filter/', AppointmentFilterView.as_view(), name='appointments_filter'),
    path('appointments-create/', AppointmentCreateView.as_view(), name='appointments_create'),

]

Pet_Health_Care_System/Pet_Cus_Info_Mng/forms.py
from django import forms
from .models import Pet, Customer

class CustomerForm(forms.Form):
    lastName = forms.CharField(label="lastName", max_length=100)
    firstName = forms.CharField(label="firstName", max_length=100)
    email = forms.EmailField(label="E-mail", max_length=255)
    phoneNumber = forms.CharField(label="phoneNumber", max_length=15)
    address = forms.CharField(label="address", max_length=255)
    age = forms.IntegerField(label="age")
    gender = forms.ChoiceField(
        label="gender",
        choices=[("Nam", "Nam"), ("Nữ", "Nữ"), ("LGBT", "LGBT")]
    )

class PetForm(forms.Form):
    name = forms.CharField(label="name", max_length=100)  
    species = forms.CharField(label="species", max_length=50)  
    gender = forms.ChoiceField(
        label="gender",
        choices=[("Đực", "Đực"), ("Cái", "Cái")],  # Lựa chọn giới tính
    )
    dateOfBirth = forms.DateField(
        label="dateOfBirht",
        widget=forms.DateInput(attrs={"type": "date"}), 
    )
    age = forms.IntegerField(
        label="age",
        required=False,
    )
    healthStatus = forms.ChoiceField(
        label="healthStatus",
        choices=[
            ('Đang nhập viện', 'Đang nhập viện'),
            ('Đang điều trị ngoại trú', 'Đang điều trị ngoại trú'),
            ('Đã xuất viện', 'Đã xuất viện'),
            ('Sức khỏe tốt','Sức khỏe tốt'),
            ('Cần tiêm phòng','Cần tiêm phòng'),
            ('Béo phì','Béo phì'),
            ('Bị chấn thương','Bị chấn thương'),
            ('Dinh dưỡng kém','Dinh dưỡng kém'),
            ('Giai đoạn cuối','Giai đoạn cuối'),
        ], 
    )
    owner = forms.ChoiceField(
        label="owner",
        choices=[]
    )

class MedicalRecordsForm(forms.Form):
    pet = forms.ChoiceField(
        label="Pet",
        choices=[],
        required=True
    )
    date = forms.DateField(label="Date", widget=forms.DateInput(attrs={'type': 'date'}))
    treatmentDetails = forms.CharField(
        label="Treatment Details",
        widget=forms.Textarea(attrs={'rows': 3}),
        required=True
    )
    doctor = forms.CharField(label="Doctor", max_length=255, required=True)
    remarks = forms.CharField(
        label="Remarks",
        widget=forms.Textarea(attrs={'rows': 3}),
        required=False
    )
    # Khởi tạo để thêm choices cho trường pet
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['pet'].choices = [(pet.id, pet.name) for pet in Pet.objects.all()]


class AppointmentsForm(forms.Form):
    customer = forms.ChoiceField(label="Customer", choices=[], required=True)
    pet = forms.ChoiceField(label="Pet", choices=[], required=True)
    date = forms.DateField(label="Date", widget=forms.DateInput(attrs={'type': 'date'}))
    time = forms.TimeField(label="Time", widget=forms.TimeInput(attrs={'type': 'time'}))
    status = forms.ChoiceField(
        label="Status",
        choices=[('pending', 'Chưa thanh toán'), ('completed', 'Đã thanh toán')],
        required=True
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        customers = Customer.objects.all()
        pets = Pet.objects.all()

        self.fields['customer'].choices = [('', '--Chọn khách hàng--')] + [
            (customer.email, f"{customer.lastName} {customer.firstName}") for customer in customers
        ]
        self.fields['pet'].choices = [('', '--Chọn thú cưng--')] + [
            (pet.id, pet.name) for pet in pets
        ]
        

Pet_Health_Care_System/Pet_Cus_Info_Mng/templates/Pet_Cus_Info_Mng/appointments-filter.html
{% extends "app_admin/master-page.html" %}

{%block header%}
    {% include 'includes/header.html' %}
{% endblock %}


{%block navbar%}
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar" style="background-color: #fff !important";>
  <div class="container">
    <a class="navbar-brand" href="{% url 'app_admin' %}"><span class="flaticon-pawprint-1 mr-2"></span>Pet Health Care System</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="fa fa-bars"></span> Menu
    </button>
    <div class="collapse navbar-collapse" id="ftco-nav">
      <ul class="navbar-nav ml-auto">
				<li class="nav-item"><a href="{% url 'customer_list' %}" class="nav-link">Khách Hàng</a></li>
        <li class="nav-item"><a href="{% url 'pet_listt' %}" class="nav-link">Thú cưng 1</a></li>
        <li class="nav-item"><a href="{% url 'pet_list' %}" class="nav-link">Thú cưng 2</a></li>
        <li class="nav-item"><a href="{% url 'medication_list' %}" class="nav-link">Thuốc điều trị</a></li>
				<li class="nav-item"><a href="{% url 'appointments_list' %}" class="nav-link">Lịch hẹn</a></li>
      </ul>
    </div>
  </div>
</nav>
{% endblock %}


{%block contactformsection%}
<div class="container mt-5">
    <h2>Lọc Lịch Hẹn</h2>
    <form method="get" action="{% url 'appointments_filter' %}">
        <label for="date">Ngày:</label>
        <input type="date" id="date" name="date">
        <label for="status">Trạng Thái:</label>
        <select id="status" name="status">
            <option value="choice">Chọn</option>
            <option value="pending">Chưa thanh toán</option>
            <option value="completed">Đã thanh toán</option>
        </select>
        <button type="submit" class="btn btn-primary">Lọc</button>
    </form>

    <h3 class="mt-4">Kết Quả</h3>
    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>Ngày</th>
                <th>Thời Gian</th>
                <th>Thú Cưng</th>   
                <th>Trạng Thái</th>
            </tr>
        </thead>
        <tbody>
            {% for appointment in appointments %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ appointment.date }}</td>
                <td>{{ appointment.time }}</td>
                <td>{{ appointment.pet }}</td>
                <td>{{ appointment.status }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}


{%block footer%}
    {% include 'includes/footer.html' %}
{% endblock %}

Pet_Health_Care_System/Pet_Cus_Info_Mng/templates/Pet_Cus_Info_Mng/appointments-history.html
{% extends "app_admin/master-page.html" %}

{%block header%}
    {% include 'includes/header.html' %}
{% endblock %}

{%block navbar%}
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar" style="background-color: #fff !important";>
  <div class="container">
    <a class="navbar-brand" href="{% url 'app_admin' %}"><span class="flaticon-pawprint-1 mr-2"></span>Pet Health Care System</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="fa fa-bars"></span> Menu
    </button>
    <div class="collapse navbar-collapse" id="ftco-nav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item"><a href="{% url 'customer_list' %}" class="nav-link">Khách Hàng</a></li>
        <li class="nav-item"><a href="{% url 'pet_listt' %}" class="nav-link">Thú cưng 1</a></li>
        <li class="nav-item"><a href="{% url 'pet_list' %}" class="nav-link">Thú cưng 2</a></li>
        <li class="nav-item"><a href="{% url 'medication_list' %}" class="nav-link">Thuốc điều trị</a></li>
        <li class="nav-item"><a href="{% url 'appointments_list' %}" class="nav-link">Lịch hẹn</a></li>
      </ul>
    </div>
  </div>
</nav>
{% endblock %}


{% block contactformsection %}
<h2>LỊCH SỬ ĐẶT LỊCH CHO: {{ appointments.0.customer.email }}</h2>
<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>#</th>
            <th>Ngày</th>
            <th>Thời gian</th>
            <th>Thú cưng</th>
            <th>Tình trạng</th>
        </tr>
    </thead>
    <tbody>
        {% if appointments %}
            {% for appointment in appointments %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ appointment.date|date:"d/m/Y" }}</td>
                <td>{{ appointment.time|time:"H:i" }}</td>
                <td>{{ appointment.pet.name }}</td>
                <td>
                    {% if appointment.status == "pending" %}
                        <span class="badge bg-warning text-dark">Chưa thanh toán</span>
                    {% elif appointment.status == "completed" %}
                        <span class="badge bg-success" style="color: #333">Đã thanh toán</span>
                    {% else %}
                        <span class="badge bg-secondary">Không xác định</span>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        {% else %}
            <tr>
                <td colspan="5" class="text-center">Không có lịch hẹn nào.</td>
            </tr>
        {% endif %}
    </tbody>
</table>

<!-- Bootstrap JS -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
{% endblock %}


{%block footer%}
    {% include 'includes/footer.html' %}
{% endblock %}

Pet_Health_Care_System/Pet_Cus_Info_Mng/templates/Pet_Cus_Info_Mng/customer_edit.html
{% extends "app_admin/master-page.html" %}

{%block header%}
    {% include 'includes/header.html' %}
{% endblock %}
<!--......................................................................................................-->
{%block navbar%}
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
    <div class="container">
        <a class="navbar-brand" href="{% url 'app_admin' %}"><span class="flaticon-pawprint-1 mr-2"></span>Pet Health Care System</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="fa fa-bars"></span> Menu
    </button>
    </div>
</nav>
{% endblock %}
<!--......................................................................................................-->

{% block contactformsection %}
<h2 style="padding: 20px";>CHỈNH SỬA THÔNG TIN KHÁCH HÀNG</h2>
<form method="post">
    {% csrf_token %}
    <div class="row">
        <div class="col-xxl">
            <div class="card mb-6" style="padding: 20px";>
                <div class="card-header d-flex align-items-center justify-content-between">
                    <h5 class="mb-0">Thông tin khách hàng</h5>
                    <small class="text-muted float-end">Điền thông tin cần sửa</small>
                </div>
                <div class="card-body">
                    <!-- Họ và tên -->
                    <div class="row mb-3">
                        <label class="col-sm-2 col-form-label" for="id_lastName">Họ</label>
                        <div class="col-sm-10">
                            <div class="input-group input-group-merge">
                                <span class="input-group-text"><i class="bx bx-user"></i></span>
                                {{ form.lastName }}
                            </div>
                        </div>
                    </div>
                    
                    <div class="row mb-3">
                        <label class="col-sm-2 col-form-label" for="id_firstName">Tên</label>
                        <div class="col-sm-10">
                            <div class="input-group input-group-merge">
                                <span class="input-group-text"><i class="bx bx-user"></i></span>
                                {{ form.firstName }}
                            </div>
                        </div>
                    </div>

                    <!-- Email -->
                    <div class="row mb-3">
                        <label class="col-sm-2 col-form-label" for="id_email">Email</label>
                        <div class="col-sm-10">
                            <div class="input-group input-group-merge">
                                <span class="input-group-text"><i class="bx bx-envelope"></i></span>
                                {{ form.email }}
                            </div>
                        </div>
                    </div>

                    <!-- Số điện thoại -->
                    <div class="row mb-3">
                        <label class="col-sm-2 col-form-label" for="id_phoneNumber">Số điện thoại</label>
                        <div class="col-sm-10">
                            <div class="input-group input-group-merge">
                                <span class="input-group-text"><i class="bx bx-phone"></i></span>
                                {{ form.phoneNumber }}
                            </div>
                        </div>
                    </div>

                    <!-- Địa chỉ -->
                    <div class="row mb-3">
                        <label class="col-sm-2 col-form-label" for="id_address">Địa chỉ</label>
                        <div class="col-sm-10">
                            <div class="input-group input-group-merge">
                                <span class="input-group-text"><i class="bx bx-map"></i></span>
                                {{ form.address }}
                            </div>
                        </div>
                    </div>

                    <!-- Tuổi -->
                    <div class="row mb-3">
                        <label class="col-sm-2 col-form-label" for="id_age">Tuổi</label>
                        <div class="col-sm-10">
                            <div class="input-group input-group-merge">
                                <span class="input-group-text"><i class="bx bx-calendar"></i></span>
                                {{ form.age }}
                            </div>
                        </div>
                    </div>

                    <!-- Giới tính -->
                    <div class="row mb-3">
                        <label class="col-sm-2 col-form-label" for="id_gender">Giới tính</label>
                        <div class="col-sm-10">
                            <div class="input-group input-group-merge">
                                <span class="input-group-text"><i class="bx bx-male"></i></span>
                                {{ form.gender }}
                            </div>
                        </div>
                    </div>

                    <!-- Nút lưu -->
                    <div class="row justify-content-end">
                        <div class="col-sm-10">
                            <button type="submit" class="btn btn-primary">Lưu</button>
                            <a id="cancel-link" href="{% url 'customer_list' %}" class="btn btn-secondary">Hủy</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}
<!--......................................................................................................-->

{%block footer%}
    {% include 'includes/footer.html' %}
{% endblock %}

Pet_Health_Care_System/Pet_Cus_Info_Mng/templates/Pet_Cus_Info_Mng/customer_form.html
{% extends "app_admin/master-page.html" %}

{%block header%}
    {% include 'includes/header.html' %}
{% endblock %}
<!--......................................................................................................-->
{%block navbar%}
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar" style="background-color: #fff !important";>
  <div class="container">
    <a class="navbar-brand" href="{% url 'app_admin' %}"><span class="flaticon-pawprint-1 mr-2"></span>Pet Health Care System</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="fa fa-bars"></span> Menu
    </button>
    <div class="collapse navbar-collapse" id="ftco-nav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item"><a href="{% url 'customer_list' %}" class="nav-link">Khách Hàng</a></li>
        <li class="nav-item"><a href="{% url 'pet_listt' %}" class="nav-link">Thú cưng 1</a></li>
        <li class="nav-item"><a href="{% url 'pet_list' %}" class="nav-link">Thú cưng 2</a></li>
        <li class="nav-item"><a href="{% url 'medication_list' %}" class="nav-link">Thuốc điều trị</a></li>
        <li class="nav-item"><a href="{% url 'appointments_list' %}" class="nav-link">Lịch hẹn</a></li>
      </ul>
    </div>
  </div>
</nav>
{% endblock %}
<!--......................................................................................................-->

{%block contactformsection%}
{% load static %}
<!-- Start Img-->
<div class="card-body">
    <a class="navbar-brand">THÊM THÔNG TIN KHÁCH HÀNG</a>
    <div class="d-flex align-items-start align-items-sm-center gap-6 pb-4 border-bottom">
      <img
        src="{% static 'app_admin/images/avata_cus_form.png' %}" alt="user-avatar"
        class="d-block w-px-100 h-px-100 rounded"
        style="width: 100px; height: 100px"
        id="uploadedAvatar"/>
      <div class="button-wrapper" style="padding: 15px;">
        <label for="upload" class="btn btn-primary me-3 mb-4" tabindex="0">
          <span class="d-none d-sm-block">Cập nhật ảnh mới</span>
          <i class="bx bx-upload d-block d-sm-none"></i>
          <input
            type="file"
            id="upload"
            class="account-file-input"
            hidden
            accept="image/png, image/jpeg" />
        </label>
        <button type="button" class="btn btn-outline-secondary account-image-reset mb-4">
          <i class="bx bx-reset d-block d-sm-none"></i>
          <span class="d-none d-sm-block">Khôi phục lại</span>
        </button>
        <div>Được phép JPG, GIF hoặc PNG. Kích thước tối đa 800K</div>
      </div>
    </div>
</div>
<!-- End Img -->

<!-- Start Information-->
<div class="card-body pt-4">
    <!-- Hiển thị thông báo -->
    {% if messages %}
    <div class="alert alert-success">
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    </div>
{% endif %}
    <!-- Form -->
    <form method="post">
      {% csrf_token %}
      <div class="row g-6">

        <!-- HỌ -->
        <div class="col-md-6">
            <label for="id_lastName" class="form-label">Họ</label>
            <input type="text" id="id_lastName" name="lastName" class="form-control" placeholder="Nhập họ">
            <!-- Hiển thị lỗi nếu có -->
            {% if form.lastName.errors %}
                <div class="text-danger">
                    {% for error in form.lastName.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                </div>
            {% endif %}
        </div>

        <!-- TÊN -->               
        <div class="col-md-6">
            <label for="id_firstName" class="form-label">Tên</label>
            <input type="text" id="id_firstName" name="firstName" class="form-control" placeholder="Nhập tên">
            <!-- Error -->
            {% if form.firstName.errors %}
                <div class="text-danger">
                    {% for error in form.firstName.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                </div>
            {% endif %}
        </div>

        <!-- EMAIL -->
        <div class="col-md-6">
            <label for="id_email" class="form-label">E-mail</label>
            <input type="email" id="id_email" name="email" class="form-control" placeholder="abc123@gmail.com">
            <!-- Error -->
            {% if form.email.errors %}
                <div class="text-danger">
                    {% for error in form.email.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                </div>
            {% endif %}
        </div>

        <!-- TUỔI -->
        <div class="col-md-6">
            <label for="id_age" class="form-label">Tuổi</label>
            <input type="number" id="id_age" name="age" class="form-control" placeholder="Nhập tuổi" min="0">
            <!-- Error -->
            {% if form.age.errors %}
                <div class="text-danger">
                    {% for error in form.age.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                </div>
            {% endif %}
        </div>        

        <!-- SỐ ĐIỆN THOẠI -->
        <div class="col-md-6">
            <label class="form-label" for="id_phoneNumber">Số điện thoại</label>
            <input type="text" id="id_phoneNumber" name="phoneNumber" class="form-control" placeholder="0123-456-789">
            <!-- Error -->
            {% if form.phoneNumber.errors %}
                <div class="text-danger">
                    {% for error in form.phoneNumber.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                </div>
            {% endif %}
        </div>

        <!-- ĐỊA CHỈ -->
        <div class="col-md-6">
            <label for="id_address" class="form-label">Địa chỉ</label>
            <input type="text" id="id_address" name="address" class="form-control" placeholder="Địa chỉ">
            <!-- Error -->
            {% if form.address.errors %}
                <div class="text-danger">
                    {% for error in form.address.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                </div>
            {% endif %}
        </div>

        <!-- GIỚI TÍNH -->
        <div class="col-md-6" style="padding: 20px;">
            <label for="id_gender" class="form-label">Giới tính</label>
            <select id="id_gender" name="gender" class="form-control">
                <option value="">Chọn giới tính</option>
                <option value="Nam">Nam</option>
                <option value="Nữ">Nữ</option>
                <option value="LGBT">LGBT</option>
            </select>
            <!-- Error -->
            {% if form.gender.errors %}
                <div class="text-danger">
                    {% for error in form.gender.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
      </div>

      <!-- Nút gửi -->
      <div class="mt-6" style="padding: 0 15px 0 15px;">
        <button type="submit" class="btn btn-primary" style="margin-top: 20px;">Tạo khách hàng</button>
        <a id="cancel-link" href="{% url 'customer_list' %}" class="btn btn-outline-secondary" style="margin-top: 20px;">Hủy</a>
      </div>
    </form>
</div>
<!-- End Information -->
{% endblock %}
<!--......................................................................................................-->

{%block footer%}
    {% include 'includes/footer.html' %}
{% endblock %}

Pet_Health_Care_System/Pet_Cus_Info_Mng/templates/Pet_Cus_Info_Mng/pet_confirm.html
{% extends "app_admin/master-page.html" %}

{%block header%}
    {% include 'includes/header.html' %}
{% endblock %}

{%block navbar%}
    {% include 'includes/nav-bar.html' %}
{% endblock %}

{%block footer%}
    {% include 'includes/footer.html' %}
{% endblock %}

Pet_Health_Care_System/Pet_Cus_Info_Mng/templates/Pet_Cus_Info_Mng/pet_edit.html
{% extends "app_admin/master-page.html" %}

{%block header%}
    {% include 'includes/header.html' %}
{% endblock %}


{%block navbar%}
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
  <div class="container">
    <a class="navbar-brand" href="{% url 'app_admin' %}"><span class="flaticon-pawprint-1 mr-2"></span>Pet Health Care System</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="fa fa-bars"></span> Menu
    </button>
  </div>
</nav>
{% endblock %}

{%block contactformsection%}
<h2 style="padding: 20px";>CHỈNH SỬA THÔNG TIN THÚ CƯNG</h2>
<form method="POST">
    {% csrf_token %}
    <div class="row">
        <div class="col-xxl">
            <div class="card mb-6" style="padding: 20px";>
                <div class="card-header d-flex align-items-center justify-content-between">
                    <h5 class="mb-0">Thông tin thú cưng</h5>
                    <small class="text-muted float-end">Điền thông tin cần sửa</small>
                </div>
                <div class="card-body">
                    <!--Tên thú cưng -->
                    <div class="row mb-3">
                        <label>Tên thú cưng</label>
                        <label class="col-sm-2 col-form-label" for="id_name"></label>
                        <div class="col-sm-10">
                            <div class="input-group input-group-merge">
                                <span class="input-group-text"><i class="bx bx-user"></i></span>
                                {{ form.name }}
                            </div>
                        </div>
                    </div>

                    <!-- Giống loài -->
                    <div class="row mb-3">
                        <label>Giống loài</label>
                        <label class="col-sm-2 col-form-label" for="id_species"></label>
                        <div class="col-sm-10">
                            <div class="input-group input-group-merge">
                                <span class="input-group-text"><i class="bx bx-user"></i></span>
                                {{ form.species }}
                            </div>
                        </div>
                    </div>

                    <!-- Tình trạng thú cưng -->
                    <div class="row mb-3">
                        <label>Tình trạng thú cưng</label>
                        <label class="col-sm-2 col-form-label" for="id_healthStatus"></label>
                        <div class="col-sm-10">
                            <div class="input-group input-group-merge">
                                <span class="input-group-text"><i class="bx bx-user"></i></span>
                                {{ form.healthStatus }}
                            </div>
                        </div>
                    </div>

                    <!-- Giới tính -->
                    <div class="row mb-3">
                        <label>Giới tính</label>
                        <label class="col-sm-2 col-form-label" for="id_gender"></label>
                        <div class="col-sm-10">
                            <div class="input-group input-group-merge">
                                <span class="input-group-text"><i class="bx bx-user"></i></span>
                                {{ form.gender }}
                            </div>
                        </div>
                    </div>

                    <!-- Chủ sỡ hữu -->
                    <div class="row mb-3">
                        <label>Chủ sở hữu</label>
                        <label class="col-sm-2 col-form-label" for="id_owner"></label>
                        <div class="col-sm-10">
                            <div class="input-group input-group-merge">
                                <span class="input-group-text"><i class="bx bx-user"></i></span>
                                {{ form.owner }}
                            </div>
                        </div>
                    </div>

                    <!-- Nút lưu -->
                    <div class="row justify-content-end">
                        <div class="col-sm-10">
                            <button type="submit" class="btn btn-primary">Lưu</button>
                            <a id="cancel-link" href="{% url 'pet_listt' %}" class="btn btn-secondary">Hủy</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}

{%block footer%}
    {% include 'includes/footer.html' %}
{% endblock %}